name: pr-checker

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - name: Installing Amplify
        run: npm install -g @aws-amplify/cli
      
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash

      - name: Installing dependencies
        run: npm install

      - name: Building
        run: npm run build
