name: pr-checker

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - name: Run build script
        run: |
          cd src && pwd
          cat export.js
          mv export.js aws-exports.js
          ls -a .
          
          echo "showing aws-exports..."
          cat aws-exports.js
          cd ..
        shell: bash

      # - name: Installing dependencies
      #   run: npm install

      # - name: Building
      #   run: npm run build
